name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'codewars/agda' }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/agda:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Example
        run: bin/run
